[package]
name = "spaces"
description = "Set/space primitives for defining machine learning problems."

version = "4.7.1"
authors = ["Tom Spooner <t.spooner@liverpool.ac.uk>"]

license = "MIT"
readme = "README.md"

keywords = ["geometry", "vector", "spaces", "machine", "learning"]

repository = "https://github.com/tspooner/spaces"
documentation = "https://docs.rs/spaces"

[badges]
travis-ci = { repository = "tspooner/spaces", branch = "master" }
coveralls = { repository = "tspooner/spaces", branch = "master", service = "github" }

[dependencies]
ndarray = { version = "0.12", features = ["serde-1"] }
itertools = "0.8"
num-traits = "0.2"

serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
serde_test = "1.0"
